#this is context properties
#Wed Sep 23 09:56:49 CEST 2026
connection_local_Login=IICS_SQL
connection_local_Database=AdventureWorks2019
connection_local_Port=1433
connection_local_Password=enc\:routine.encryption.key.v1\:mgkklp5NYZlCYu8TDF48PPfkiWf+uYKnwLG/NR0a49ck4Gf0
connection_local_AdditionalParams=
connection_local_Schema=Sales
connection_local_Server=localhost
