#this is context properties
#Wed Sep 23 09:45:19 CEST 2026
local_Login=IICS_SQL
local_Database=AdventureWorks2019
local_Port=1433
local_Password=enc\:routine.encryption.key.v1\:8Hm5RjWXoLzKvTRT/UyniNTZkGWUpX2gc3gUOCWDB3l/vteQ
local_AdditionalParams=
local_Schema=Sales
local_Server=localhost
